/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Ballots: () => import('#controllers/ballots_controller'),
  Entries: () => import('#controllers/entries_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Leaderboard: () => import('#controllers/leaderboard_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Rounds: () => import('#controllers/rounds_controller'),
  Shots: () => import('#controllers/shots_controller'),
  Telemetry: () => import('#controllers/telemetry_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
