/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Ballots: () => import('#controllers/ballots_controller'),
  Entries: () => import('#controllers/entries_controller'),
  Leaderboard: () => import('#controllers/leaderboard_controller'),
  Rounds: () => import('#controllers/rounds_controller'),
  Telemetry: () => import('#controllers/telemetry_controller'),
}
